### ISSUE TITLE
Corrections and generalization

### ISSUE THREAD

**Issue by audeser** [gpolic/k-means-excel#1]
There are some syntax variables declaration incorrectness, so they pretend to be declared as some type, but they get declared as Variants in VBA (f.e.: `Dim i, j as long` is incorrect, correct syntax is like: `Dim i as long, j as long`)
Once an array variable is declared as some type, the forward ReDim declaration as any type -even if the same- is not totally correct. ReDim should there be used to allocate memory (f.e. `Dim myArr( ) as integer: ReDim myArr(0) as integer` is not correct)

On the procedure where centroids are initialized, the For-Loop: `For counter = NumRecords To 1` is incorrect, as it should be `For counter = NumRecords To 1 Step -1` . Also, in this loop, once a value is found, better off to "Exit For"

On the main procedure, Application.StatusBar should be returned to "" or even better, to OldStatus (new variable). Same for ScreenUpdating. On attached files, code related to this issue is commented.

Done a generalization of this algorithm, just not to be of use for range data but for Variant data (wherever it comes and wherever the Base index is)... even it's working with Base 0 data, not yet got rid of Option Base 1 in order to not bother user. In order to get a nice view of what is done, performed a View arrangement (AutoOpen triggered).

Added image from Wikipedia: [Dataset image](https://en.wikipedia.org/wiki/Iris_flower_data_set#/media/File:Iris_dataset_scatterplot.svg) to get a feeling of the data in the sample. Also added a chart to show data (3 series for 3 clusters + 1 serie for centroids), even if chart series address should be reworked after every Cluster calculation (prior data should be sorted out by cluster Id).

Attached is new code and sample workbook. Aside from rearranged modules and general flow, beautified the code comments 

Best regards

[k-means_updated.zip](https://github.com/gpolic/kmeans-excel/files/9722137/k-means_updated.zip)

**Comment by DmKUser** [comment]
Thanks
Type mismatch when calculating new centoids for each cluster
Better use clusters range (min,max) to optimise for max GAP value

**Comment by gpolic** [comment]
Thank you for taking the time to improve the code. I have not checked this for a long time.
Please feel free to clone and add this to your projects along with the improvements, or create a pull request here

**Comment by gpolic** [comment]
I found some opportunity to look into this.

Adjusted the variable definitions, and variable names
Fixed the For Loop with "Step -1"
Also included some changes for readability
