### ISSUE TITLE
XLSM not available

### ISSUE THREAD

**Issue by MilesAheadToo** [gpolic/k-means-excel#3]
I have tried loading the VBA code into my own XLS but there are lots of references that are incorrect and are not mentioned in the documentation, for example:
`    Dim MaximumIterations As Integer: MaximumIterations = wkSheet.Range("MaximumIterations").Value
    Dim DataSht As String: DataSht = wkSheet.Range("InputSheet").Value
    Dim DataRange As String: DataRange = wkSheet.Range("InputRange").Value
    Dim DataRecords As Variant: DataRecords = Worksheets(DataSht).Range(DataRange)`

**Comment by gpolic** [comment]
These "ranges" are references to some data in the Excel file, on the first sheet called "Start"
Check out Column C on the first sheet, and you have all the input data. Their names are in Column B and a short description in Column E. 
You can assign these variables to your preference.
